/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all collection codenames
 */
export const collectionCodenames = ['default'] as const;

/*
 * Type representing all collection codenames
 */
export type CollectionCodenames = (typeof collectionCodenames)[number];

/*
 * Typeguard for collection codename
 */
export function isCollectionCodename(value: string | undefined | null): value is CollectionCodenames {
	return typeof value === 'string' && (collectionCodenames as readonly string[]).includes(value);
}
