/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all taxonomy codenames
 */
export const taxonomyCodenames = ['fdsafas', 'fdsafsdaf'] as const;

/*
 * Type representing all taxonomy codenames
 */
export type TaxonomyCodenames = (typeof taxonomyCodenames)[number];

/*
 * Typeguard for taxonomy codename
 */
export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
	return typeof value === 'string' && (taxonomyCodenames as readonly string[]).includes(value);
}
