/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from './_taxonomies.js';

/*
 * Type representing codename of 'fdsafsdaf' taxonomy
 */
export type FdsafsdafTaxonomyCodename = Extract<TaxonomyCodenames, 'fdsafsdaf'>;

/*
 * Typeguard for codename of 'fdsafsdaf' taxonomy
 */
export function isFdsafsdafTaxonomyCodename(value: string | undefined | null): value is FdsafsdafTaxonomyCodename {
	return typeof value === 'string' && value === ('fdsafsdaf' satisfies FdsafsdafTaxonomyCodename);
}

/*
 * Array of all taxonomy term codenames
 */
export const fdsafsdafTaxonomyTermCodenames = ['vcxzvdfsa'] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type FdsafsdafTaxonomyTermCodenames = (typeof fdsafsdafTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isFdsafsdafTaxonomyTermCodename(value: string | undefined | null): value is FdsafsdafTaxonomyTermCodenames {
	return typeof value === 'string' && (fdsafsdafTaxonomyTermCodenames as readonly string[]).includes(value);
}
