/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from './_taxonomies.js';

/*
 * Type representing codename of 'fdsafas' taxonomy
 */
export type FdsafasTaxonomyCodename = Extract<TaxonomyCodenames, 'fdsafas'>;

/*
 * Typeguard for codename of 'fdsafas' taxonomy
 */
export function isFdsafasTaxonomyCodename(value: string | undefined | null): value is FdsafasTaxonomyCodename {
	return typeof value === 'string' && value === ('fdsafas' satisfies FdsafasTaxonomyCodename);
}

/*
 * Array of all taxonomy term codenames
 */
export const fdsafasTaxonomyTermCodenames = ['fdsafds'] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type FdsafasTaxonomyTermCodenames = (typeof fdsafasTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isFdsafasTaxonomyTermCodename(value: string | undefined | null): value is FdsafasTaxonomyTermCodenames {
	return typeof value === 'string' && (fdsafasTaxonomyTermCodenames as readonly string[]).includes(value);
}
