/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all language codenames
 */
export const languageCodenames = ['default'] as const;

/*
 * Type representing all language codenames
 */
export type LanguageCodenames = (typeof languageCodenames)[number];

/*
 * Typeguard for language codename
 */
export function isLanguageCodename(value: string | undefined | null): value is LanguageCodenames {
	return typeof value === 'string' && (languageCodenames as readonly string[]).includes(value);
}
