/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from './_languages.js';

/*
 * Type representing codename of 'Default project language' language
 */
export type DefaultLanguageCodename = Extract<LanguageCodenames, 'default'>;

/*
 * Typeguard for codename of 'Default project language' language
 */
export function isDefaultLanguageCodename(value: string | undefined | null): value is DefaultLanguageCodename {
	return typeof value === 'string' && value === ('default' satisfies DefaultLanguageCodename);
}
