/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

import type { TypeCodenames } from './_types.js';
import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreType } from '../system/index.js';

/*
 * Type representing codename of 'Smart Link Parent Item' type
 */
export type SmartLinkParentItemTypeCodename = Extract<TypeCodenames, 'smart_link_parent_item'>;

/*
 * Typeguard for codename of 'Smart Link Parent Item' type
 */
export function isSmartLinkParentItemTypeCodename(value: string | undefined | null): value is SmartLinkParentItemTypeCodename {
	return typeof value === 'string' && value === ('smart_link_parent_item' satisfies SmartLinkParentItemTypeCodename);
}

/*
 * Smart Link Parent Item
 *
 * Id: 3a35a3e5-9db2-4f42-8129-0edccaf91d41
 * Codename: smart_link_parent_item
 */
export type SmartLinkParentItemType = CoreType<
	SmartLinkParentItemTypeElementCodenames,
	{
		/*
		 * Test Text
		 *
		 * Codename: test_text
		 * Id: 62515aca-3174-4414-a123-2ec2e28a9696
		 * Type: text
		 * Required: false
		 */
		readonly test_text: Elements.TextElement;

		/*
		 * Test Rich Text
		 *
		 * Codename: test_rich_text
		 * Id: 18b149ea-281b-4d87-814f-f86fd91e6b41
		 * Type: rich_text
		 * Required: false
		 */
		readonly test_rich_text: Elements.RichTextElement<CoreType>;

		/*
		 * Test Linked Items
		 *
		 * Codename: test_linked_items
		 * Id: 181043ca-ce45-48fa-8e03-fc683c3c0832
		 * Type: modular_content
		 * Required: false
		 */
		readonly test_linked_items: Elements.LinkedItemsElement<CoreType>;
	},
	SmartLinkParentItemTypeCodename
>;

/*
 * Type representing all available element codenames for Smart Link Parent Item
 */
export type SmartLinkParentItemTypeElementCodenames = 'test_text' | 'test_rich_text' | 'test_linked_items';

/*
 * Type guard for Smart Link Parent Item
 *
 * Id: 3a35a3e5-9db2-4f42-8129-0edccaf91d41
 * Codename: smart_link_parent_item
 */
export function isSmartLinkParentItemType(item: CoreType | undefined | null): item is SmartLinkParentItemType {
	return item?.system?.type === ('smart_link_parent_item' satisfies SmartLinkParentItemTypeCodename);
}
