/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

import type { TypeCodenames } from './_types.js';
import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreType } from '../system/index.js';
import type { SmartLinkLinkedItemType } from './index.js';

/*
 * Type representing codename of 'Smart Link Component' type
 */
export type SmartLinkComponentTypeCodename = Extract<TypeCodenames, 'smart_link_component'>;

/*
 * Typeguard for codename of 'Smart Link Component' type
 */
export function isSmartLinkComponentTypeCodename(value: string | undefined | null): value is SmartLinkComponentTypeCodename {
	return typeof value === 'string' && value === ('smart_link_component' satisfies SmartLinkComponentTypeCodename);
}

/*
 * Smart Link Component
 *
 * Id: c01bd245-ac2d-4e01-b10f-b3b8fc61fb71
 * Codename: smart_link_component
 */
export type SmartLinkComponentType = CoreType<
	SmartLinkComponentTypeElementCodenames,
	{
		/*
		 * Title
		 *
		 * Codename: title
		 * Id: 68025bce-af0b-4821-af3e-194b7c34d029
		 * Type: text
		 * Required: false
		 */
		readonly title: Elements.TextElement;

		/*
		 * Rich Text
		 *
		 * Codename: rich_text
		 * Id: d695a912-ae7b-4a17-887f-eeb9d4089d19
		 * Type: rich_text
		 * Required: false
		 * Allowed content types: smart_link_component, smart_link_linked_item
		 */
		readonly rich_text: Elements.RichTextElement<SmartLinkComponentType | SmartLinkLinkedItemType>;

		/*
		 * Linked Items
		 *
		 * Codename: linked_items
		 * Id: f51edba0-80a9-4626-94f4-d79a05eab4af
		 * Type: modular_content
		 * Required: false
		 * Allowed content types: smart_link_linked_item
		 */
		readonly linked_items: Elements.LinkedItemsElement<SmartLinkLinkedItemType>;
	},
	SmartLinkComponentTypeCodename
>;

/*
 * Type representing all available element codenames for Smart Link Component
 */
export type SmartLinkComponentTypeElementCodenames = 'title' | 'rich_text' | 'linked_items';

/*
 * Type guard for Smart Link Component
 *
 * Id: c01bd245-ac2d-4e01-b10f-b3b8fc61fb71
 * Codename: smart_link_component
 */
export function isSmartLinkComponentType(item: CoreType | undefined | null): item is SmartLinkComponentType {
	return item?.system?.type === ('smart_link_component' satisfies SmartLinkComponentTypeCodename);
}
