/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

import type { TypeCodenames } from './_types.js';
import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreType } from '../system/index.js';
import type { SmartLinkComponentType } from './index.js';

/*
 * Type representing codename of 'Smart Link Linked Item' type
 */
export type SmartLinkLinkedItemTypeCodename = Extract<TypeCodenames, 'smart_link_linked_item'>;

/*
 * Typeguard for codename of 'Smart Link Linked Item' type
 */
export function isSmartLinkLinkedItemTypeCodename(value: string | undefined | null): value is SmartLinkLinkedItemTypeCodename {
	return typeof value === 'string' && value === ('smart_link_linked_item' satisfies SmartLinkLinkedItemTypeCodename);
}

/*
 * Smart Link Linked Item
 *
 * Id: 701e4268-9461-4142-8036-e3e67d549121
 * Codename: smart_link_linked_item
 */
export type SmartLinkLinkedItemType = CoreType<
	SmartLinkLinkedItemTypeElementCodenames,
	{
		/*
		 * Title
		 *
		 * Codename: title
		 * Id: ce0634e5-7388-4c3d-aaf5-ca1d53ff4153
		 * Type: text
		 * Required: false
		 */
		readonly title: Elements.TextElement;

		/*
		 * Rich Text
		 *
		 * Codename: rich_text
		 * Id: e342af27-a42f-4f8e-aea1-51524ade86f0
		 * Type: rich_text
		 * Required: false
		 * Allowed content types: smart_link_linked_item, smart_link_component
		 */
		readonly rich_text: Elements.RichTextElement<SmartLinkLinkedItemType | SmartLinkComponentType>;

		/*
		 * Linked Items
		 *
		 * Codename: linked_items
		 * Id: 6b3bcee1-7a52-4001-bd05-55f33c33b3d4
		 * Type: modular_content
		 * Required: false
		 * Allowed content types: smart_link_linked_item
		 */
		readonly linked_items: Elements.LinkedItemsElement<SmartLinkLinkedItemType>;
	},
	SmartLinkLinkedItemTypeCodename
>;

/*
 * Type representing all available element codenames for Smart Link Linked Item
 */
export type SmartLinkLinkedItemTypeElementCodenames = 'title' | 'rich_text' | 'linked_items';

/*
 * Type guard for Smart Link Linked Item
 *
 * Id: 701e4268-9461-4142-8036-e3e67d549121
 * Codename: smart_link_linked_item
 */
export function isSmartLinkLinkedItemType(item: CoreType | undefined | null): item is SmartLinkLinkedItemType {
	return item?.system?.type === ('smart_link_linked_item' satisfies SmartLinkLinkedItemTypeCodename);
}
