/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

import type { TypeCodenames } from './_types.js';
import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreType } from '../system/index.js';

/*
 * Type representing codename of 'Web spotlight root' type
 */
export type WebSpotlightRootTypeCodename = Extract<TypeCodenames, 'web_spotlight_root'>;

/*
 * Typeguard for codename of 'Web spotlight root' type
 */
export function isWebSpotlightRootTypeCodename(value: string | undefined | null): value is WebSpotlightRootTypeCodename {
	return typeof value === 'string' && value === ('web_spotlight_root' satisfies WebSpotlightRootTypeCodename);
}

/*
 * Web spotlight root
 *
 * Id: bb4ca8b2-5bdb-43c9-b49e-e384b556ffb3
 * Codename: web_spotlight_root
 */
export type WebSpotlightRootType = CoreType<
	WebSpotlightRootTypeElementCodenames,
	{
		/*
		 * Title
		 *
		 * Codename: title
		 * Id: 5698f3f1-3059-473f-b4ae-8d2e8d58d974
		 * Type: text
		 * Required: false
		 */
		readonly title: Elements.TextElement;

		/*
		 * Subpages
		 *
		 * Codename: subpages
		 * Id: 03f727f8-a2e9-4b9f-99e4-c03345491d52
		 * Type: subpages
		 * Required: false
		 */
		readonly subpages: Elements.LinkedItemsElement<CoreType>;

		/*
		 * Content
		 *
		 * Codename: content
		 * Id: cab31439-e3d2-4c4e-a0c7-2f1fe56482b1
		 * Type: modular_content
		 * Required: false
		 */
		readonly content: Elements.LinkedItemsElement<CoreType>;
	},
	WebSpotlightRootTypeCodename
>;

/*
 * Type representing all available element codenames for Web spotlight root
 */
export type WebSpotlightRootTypeElementCodenames = 'title' | 'subpages' | 'content';

/*
 * Type guard for Web spotlight root
 *
 * Id: bb4ca8b2-5bdb-43c9-b49e-e384b556ffb3
 * Codename: web_spotlight_root
 */
export function isWebSpotlightRootType(item: CoreType | undefined | null): item is WebSpotlightRootType {
	return item?.system?.type === ('web_spotlight_root' satisfies WebSpotlightRootTypeCodename);
}
