/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all workflow codenames
 */
export const workflowCodenames = ['default'] as const;

/*
 * Type representing all workflow codenames
 */
export type WorkflowCodenames = (typeof workflowCodenames)[number];

/*
 * Typeguard for workflow codename
 */
export function isWorkflowCodename(value: string | undefined | null): value is WorkflowCodenames {
	return typeof value === 'string' && (workflowCodenames as readonly string[]).includes(value);
}

/*
 * Array of all workflow codenames
 */
export const workflowStepCodenames = ['draft', 'published', 'archived', 'scheduled'] as const;

/*
 * Type representing all workflow codenames
 */
export type WorkflowStepCodenames = (typeof workflowStepCodenames)[number];

/*
 * Typeguard for workflow codename
 */
export function isWorkflowStepCodename(value: string | undefined | null): value is WorkflowStepCodenames {
	return typeof value === 'string' && (workflowStepCodenames as readonly string[]).includes(value);
}
