/*
 * This file has been auto-generated by '@kontent-ai/model-generator@9.0.0-5'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: SMARTLINK SDK TEST
 * Environment: Production
 * Id: 58fa9aea-7ce8-015a-f326-20f71f105ce0
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all element codenames
 */
export const elementCodenames = [
	'test_text',
	'test_rich_text',
	'test_linked_items',
	'title',
	'rich_text',
	'linked_items',
	'subpages',
	'content'
] as const;

/*
 * Type representing all element codenames
 */
export type ElementCodenames = (typeof elementCodenames)[number];

/*
 * Typeguard for element codename
 */
export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
	return typeof value === 'string' && (elementCodenames as readonly string[]).includes(value);
}
